//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PqcEmail.Outlook.Properties 
{
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase 
    {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default 
        {
            get 
            {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hybrid")]
        public string DefaultEncryptionStrategy 
        {
            get 
            {
                return ((string)(this["DefaultEncryptionStrategy"]));
            }
            set 
            {
                this["DefaultEncryptionStrategy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableHybridMode 
        {
            get 
            {
                return ((bool)(this["EnableHybridMode"]));
            }
            set 
            {
                this["EnableHybridMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoDetectRecipientCapabilities 
        {
            get 
            {
                return ((bool)(this["AutoDetectRecipientCapabilities"]));
            }
            set 
            {
                this["AutoDetectRecipientCapabilities"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RequirePqcForInternalEmails 
        {
            get 
            {
                return ((bool)(this["RequirePqcForInternalEmails"]));
            }
            set 
            {
                this["RequirePqcForInternalEmails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowSecurityBadges 
        {
            get 
            {
                return ((bool)(this["ShowSecurityBadges"]));
            }
            set 
            {
                this["ShowSecurityBadges"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowEncryptionStatusInSubject 
        {
            get 
            {
                return ((bool)(this["ShowEncryptionStatusInSubject"]));
            }
            set 
            {
                this["ShowEncryptionStatusInSubject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IconAndText")]
        public string SecurityIndicatorStyle 
        {
            get 
            {
                return ((string)(this["SecurityIndicatorStyle"]));
            }
            set 
            {
                this["SecurityIndicatorStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int CapabilityCacheTimeoutMinutes 
        {
            get 
            {
                return ((int)(this["CapabilityCacheTimeoutMinutes"]));
            }
            set 
            {
                this["CapabilityCacheTimeoutMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableBackgroundProcessing 
        {
            get 
            {
                return ((bool)(this["EnableBackgroundProcessing"]));
            }
            set 
            {
                this["EnableBackgroundProcessing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("company.com")]
        public string InternalDomains 
        {
            get 
            {
                return ((string)(this["InternalDomains"]));
            }
            set 
            {
                this["InternalDomains"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableDetailedLogging 
        {
            get 
            {
                return ((bool)(this["EnableDetailedLogging"]));
            }
            set 
            {
                this["EnableDetailedLogging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ForceSignatureValidation 
        {
            get 
            {
                return ((bool)(this["ForceSignatureValidation"]));
            }
            set 
            {
                this["ForceSignatureValidation"] = value;
            }
        }
    }
}